matrix:
  include:
    - os: xcode9.2
      language: objective-c
      osx_image: xcode9.2
      script:
        - set -o pipefail
        - swift test -Xswiftc -DDEBUG_CHANNELZ
        - xcodebuild test -sdk macosx -scheme ChannelZ | xcpretty -c
        - xcodebuild test -scheme ChannelZ -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone X,OS=11.0" | xcpretty -c
    - os: linux
      language: generic
      sudo: required
      dist: trusty
      before_install:
      - wget -q -O - https://swift.org/keys/all-keys.asc | gpg --import -
      - wget https://swift.org/builds/swift-4.0-release/ubuntu1404/swift-4.0-RELEASE/swift-4.0-RELEASE-ubuntu14.04.tar.gz
      - tar xzf swift-4.0-RELEASE-ubuntu14.04.tar.gz
      - export PATH=${PWD}/swift-4.0-RELEASE-ubuntu14.04/usr/bin:"${PATH}"
      script:
        - swift test -Xswiftc -DDEBUG_CHANNELZ

