env:
  - SWIFT_VERSION=4.2
matrix:
  include:
    - os: osx
      language: objective-c
      osx_image: xcode10
      script:
        - set -o pipefail
        - swift test -Xswiftc -DDEBUG_CHANNELZ
        - xcodebuild test -sdk macosx -scheme ChannelZ | xcpretty -c
        - xcodebuild test -scheme ChannelZ -sdk iphonesimulator -destination "platform=iOS Simulator,OS=11.2,name=iPhone X" | xcpretty -c
    - os: linux
      language: generic
      sudo: required
      dist: trusty
      install:
        - wget -q -O - https://swift.org/keys/all-keys.asc | gpg --import -
        - wget https://swift.org/builds/swift-${SWIFT_VERSION}-release/ubuntu1404/swift-${SWIFT_VERSION}-RELEASE/swift-${SWIFT_VERSION}-RELEASE-ubuntu14.04.tar.gz
        - tar xzf swift-${SWIFT_VERSION}-RELEASE-ubuntu14.04.tar.gz
        - export PATH=${PWD}/swift-${SWIFT_VERSION}-RELEASE-ubuntu14.04/usr/bin:"${PATH}"
      script:
        - swift test -Xswiftc -DDEBUG_CHANNELZ

