osx_image: xcode10.0
language: Objective-C
xcode_project: BricBrac.xcodeproj
xcode_scheme: BricBrac

script:

after_success:
  - bash <(curl -s https://codecov.io/bash)

matrix:
  include:
    - os: osx
      language: objective-c
      osx_image: xcode10.0
      script:
        - set -o pipefail
        - swift test -Xswiftc -DDEBUG_CHANNELZ
        - xcodebuild test -sdk macosx -scheme ChannelZ | xcpretty -c
        - xcodebuild test -scheme ChannelZ -sdk iphonesimulator -destination "platform=iOS Simulator,OS=11.2,name=iPhone X" | xcpretty -c
    - os: linux
      language: generic
      sudo: required
      dist: trusty
      before_install:
      - wget -q -O - https://swift.org/keys/all-keys.asc | gpg --import -
      - wget https://swift.org/builds/swift-4.2-release/ubuntu1404/swift-4.2-RELEASE/swift-4.2-RELEASE-ubuntu14.04.tar.gz
      - tar xzf swift-4.2-RELEASE-ubuntu14.04.tar.gz
      - export PATH=${PWD}/swift-4.2-RELEASE-ubuntu14.04/usr/bin:"${PATH}"
      script:
        - swift test -Xswiftc -DDEBUG_CHANNELZ

